name: 'safeAction'
description: 'This action is checking safety of other actions'
inputs:
  github-token:
    description: 'Github token'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'