name: 'safeAction'
description: 'This action is checking safety of other actions'
inputs:
  github-token:
    description: 'Github token'
    required: false
    default: ''
  mode:
    description: 'User needs to choose mode: Stop workfow or only alert send'
    required: true
    default: 'stop'
outputs:
  text: # id of output
    description: 'File:'
runs:
  using: 'node12'
  main: 'index.js'