name: 'safeAction'
description: 'This action is checking safety of other actions'
inputs:
  mode:
    description: 'User needs to choose mode: Stop workfow or only alert send'
    required: true
    default: 'SAFE'
  authorization:
    description: 'Token generated for your clientId. If no token is provided, action will check only first 3 actions in your pipeline.'
    required: false
outputs:
  text: # id of output
    description: 'File:'
runs:
  using: 'node12'
  main: 'index.js'